id: P85E42A23
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG2170
  instance_id: http://purl.bdrc.io/resource/IE1KG2170
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - སྙིང་ཐིག་སྔོན་འགྲོའི་ཁྲིད་ཡིག་ཐར་ལམ་གསལ་བྱེད་དང་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ་བཅས།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P6002
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    ed9350571f834371b13ba46148c2162a:
      title: པོད ༡་སྙིང་ཐིག་སྔོན་འགྲོའི་ཁྲིད་ཡིག་ཐར་ལམ་གསལ་བྱེད་དང་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ་བཅས།
      volume_number: 1
      base_file: UT1KG2170_I1KG2189_0000.txt
      reference: http://purl.bdrc.io/resource/VL7163DB35F66547B8
      image_group: I1KG2189
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG2170
  - http://purl.bdrc.io/resource/W1KG2170
  ocr_software: Namsel
created_at: '2021-12-22T10:37:03.727361'
last_modified_at: '2021-12-22T10:37:03.727367'
